https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

In [57]:
import torch
import numpy as np

In [11]:
print (torch.cuda.device_count())
print (torch.cuda.get_device_name())

1
Tesla K80


In [24]:
x = torch.zeros(5, 3, dtype=torch.long)
print (x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [20]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  9.1084e-44,  0.0000e+00],
        [-7.4145e-11,  4.5595e-41, -7.4145e-11]])


In [29]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0292, 0.1589, 0.9660],
        [0.1031, 0.4235, 0.4535],
        [0.8592, 0.3978, 0.5956],
        [0.8557, 0.4796, 0.2504],
        [0.5943, 0.1138, 0.1818]])


In [27]:
torch.tensor([5,3,1], dtype=torch.float)

tensor([5., 3., 1.])

In [31]:
torch.randn_like(x)

tensor([[ 1.4012,  0.1457, -0.3438],
        [-0.3696, -0.0468,  0.4342],
        [ 0.6618, -0.3977, -1.4822],
        [ 1.5573,  0.3720, -0.1694],
        [ 0.9178,  0.0404,  0.5629]])

In [35]:
print(x.shape, x.size())

torch.Size([5, 3]) torch.Size([5, 3])


In [37]:
y = torch.rand(5,3)

In [43]:
(x+y == torch.add(x,y)).all()

tensor(1, dtype=torch.uint8)

In [49]:
#in-place operators are postfixed with "_"
y.add_(1)

tensor([[4.2792, 4.1187, 4.1643],
        [4.1170, 4.0597, 4.8369],
        [4.5409, 4.2044, 4.8068],
        [4.9080, 4.9328, 4.2435],
        [4.9363, 4.7659, 4.7183]])

#### numpy bridge

In [56]:
a = torch.ones(5)
b = a.numpy()  # NOTE: reference to [a]
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [66]:
a = np.ones(5)
try:
    b = torch.ones_like(a)
except TypeError:
    print ('unable to use *_like() methods directly on numpy')
b = torch.from_numpy(a)  # again, this is in-place
np.add(a, 1, out=a)
print(a)
print(b)

unable to use *_like() methods directly on numpy
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [74]:
if torch.cuda.is_available():
    print('CUDA available')
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

CUDA available
tensor([[1.0292, 1.1589, 1.9660],
        [1.1031, 1.4235, 1.4535],
        [1.8592, 1.3978, 1.5956],
        [1.8557, 1.4796, 1.2504],
        [1.5943, 1.1138, 1.1818]], device='cuda:0')
tensor([[1.0292, 1.1589, 1.9660],
        [1.1031, 1.4235, 1.4535],
        [1.8592, 1.3978, 1.5956],
        [1.8557, 1.4796, 1.2504],
        [1.5943, 1.1138, 1.1818]], dtype=torch.float64)


## Autograd (automatic differentiation)

In [100]:
import torch

In [101]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [102]:
y = x + 2
print(y)
print(y.grad)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
None


In [103]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [104]:
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a)
b = (a * a).sum()
print(b)

False
tensor([[ 48.9152,   1.2149],
        [  1.6173, -17.3221]], requires_grad=True)
tensor(2696.8477, grad_fn=<SumBackward0>)


In [119]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()
out.backward()
print(x.grad)  # d(out)/dx

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [142]:
x = torch.randn(3, requires_grad=True)
y = x * 2
# NOTE: item() retrieves scalar from (1,) vector. alternative is: y.data.norm()
while y.norm().item() < 1000:
    y = y * 2
print(y)

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

print(x.requires_grad)
print((x ** 2).requires_grad)

# stop tracking within context manager
with torch.no_grad():
    print((x ** 2).requires_grad)


tensor([-722.8755, -472.6552, 1362.2292], grad_fn=<MulBackward0>)
tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])
True
True
False


NEXT:

https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html
